target 'Floq' do
  use_frameworks!
  pod 'FirebaseUI'
  pod 'Firebase'
  
  pod 'FacebookCore'
  pod 'FacebookLogin'

  pod 'DKImagePickerController'
  pod 'IGListKit'
  pod 'Floaty', '~> 4.0.0' # Use version 4.0.0 for Swift 4.0
  pod 'Eureka'
end
